version: '3.8'

services:
  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: nodejs
    ports:
      - "3307:3306"
    networks:
      - mynetwork
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3055:3055"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: 12345678
      DB_NAME: nodejs
      DB_PORT: 3307
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    networks:
      - mynetwork
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./redis.log:/var/log/redis/redis.log  
    networks:
      - mynetwork
  jenkins:
    restart: always
    image: jenkins
    container_name: harvey-jenkins
    volumes:
    - ./docker/jenkins:/var/jenkins_home
    expose:
    - "50000"
    - "8080"
    environment:
      - VIRTUAL_HOST=jenkins.shop-ecommerce.click
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=jenkins.shop-ecommerce.click
      - LETSENCRYPT_EMAIL=huy343536@gmail.com
networks:
  mynetwork:
    driver: bridge
volumes:
  db-data:
  redis-data:
